// @flow
import type { Styles } from '../../types/styles';

export default (): Styles => ({
  textCenter: {
    textAlign: 'center',
  },
  textInfo: {
    color: '#d14942',
    fontStyle: 'italic',
  },
  sky: {
    position: 'absolute',
    width: '100%',
    background: 'linear-gradient(-15deg,#ff6d24, #5f6b55,  #283E51, #0A2342)',
    height: '100vh',
  },
  sign: {
    position: 'absolute',
    top: 'calc(100% - 500px)',
    left: 'calc(100% - 500px)',
  },
  grass: {
    position: 'absolute',
    width: '500px',
    height: '500px',
  },
  grassBack: {
    position: 'absolute',
    left: '10%',
    top: '80%',
    width: '250px',
    height: '250px',
    MozBorderRadius: '125px',
    WebkitBorderRadius: '125px',
    borderRadius: '125px',
    background: '#154f0f',
    zIndex: '1',
  },
  grassMiddle: {
    position: 'absolute',
    left: '20%',
    top: '80%',
    width: '500px',
    height: '200px',
    MozBorderRadius: '150px / 50px',
    WebkitBorderRadius: '150px / 50px',
    borderRadius: '150px / 50px',
    transform: 'rotate(-15deg)',
    background: '#195e12',
    zIndex: '2',
  },
  grassFront: {
    position: 'absolute',
    top: '92%',
    right: '30%',
    width: '500px',
    height: '200px',
    MozBorderRadius: '250px / 50px',
    WebkitBorderRadius: '250px / 50px',
    borderRadius: '250px / 50px',
    background: '#23761a',
    zIndex: '4',
  },
  pillar: {
    position: 'absolute',
    left: '35%',
    width: '30px',
    height: '600px',
    background: '#e2e2e2',
    zIndex: '3',
  },
  pillarShadow: {
    position: 'absolute',
    width: '15px',
    height: '500px',
    background: '#d0d0d0',
    zIndex: '3',
  },
  pillarBase: {
    position: 'absolute',
    top: '71%',
    left: '-15px',
    width: '60px',
    height: '60px',
    background: '#e2e2e2',
    zIndex: '3',
  },
  pillarHead: {
    position: 'absolute',
    left: '-10px',
    width: '50px',
    height: '10px',
    background: '#e2e2e2',
    zIndex: '3',
  },
  pillarSphere: {
    position: 'absolute',
    top: '-30px',
    width: '30px',
    height: '30px',
    MozBorderRadius: '15px',
    WebkitBorderRadius: '15px',
    borderRadius: '15px',
    background: 'radial-gradient(#d0d0d0, #e2e2e2)',
    zIndex: '3',
  },
  plates: {
    position: 'relative',
    top: '40px',
    width: '400px',
    height: '350px',
    zIndex: '5',
  },
  plateTop: {
    position: 'relative',
    left: '5%',
    width: '250px',
    height: '100px',
    WebkitClipPath: 'polygon(10% 0%, 100% 1%, 100% 100%, 10% 100%, 0% 50%)',
    clipPath: 'polygon(10% 0%, 100% 1%, 100% 100%, 10% 100%, 0% 50%)',
    background: '#e4e4e4',
  },
  plateBottom: {
    position: 'relative',
    top: '0%',
    left: '25%',
    width: '250px',
    height: '100px',
    WebkitClipPath: 'polygon(10% 0%, 100% 1%, 100% 100%, 10% 100%, 0% 50%)',
    clipPath: 'polygon(10% 0%, 100% 1%, 100% 100%, 10% 100%, 0% 50%)',
    background: '#e4e4e4',
    transform: 'rotate(170deg)',
  },
  plateInner: {
    position: 'relative',
    top: '10px',
    left: '10px',
    width: '230px',
    height: '80px',
    WebkitClipPath: 'polygon(9% 0%, 100% 1%, 100% 100%, 9% 100%, 0% 50%)',
    clipPath: 'polygon(9% 0%, 100% 1%, 100% 100%, 9% 100%, 0% 50%)',
  },
  red: {
    background: '#d14942',
  },
  yellow: {
    background: '#f4c844',
  },
  plateImage: {
    position: 'relative',
    height: '51px',
    width: 'auto',
  },
  freebee: {
    position: 'relative',
    top: '19%',
    left: '13%',
  },
  misc: {
    position: 'relative',
    top: '19%',
    left: '13%',
    WebkitTransform: 'otate(180deg) translatez(0)',
    transform: 'rotate(180deg) translatez(0)',
    backfaceVisibility: 'hidden',
    filter: 'blur(0)',
  },
  nail1: {
    position: 'absolute',
    top: 'calc(50% - 5px)',
    left: '67%',
    width: '10px',
    height: '10px',
    MozBorderRadius: '5px',
    WebkitBorderRadius: '5px',
    borderRadius: '5px',
    background: '#e2e2e2',
    zIndex: '10',
  },
  nail2: {
    position: 'absolute',
    top: 'calc(50% - 5px)',
    left: '64%',
    width: '10px',
    height: '10px',
    MozBorderRadius: '5px',
    WebkitBorderRadius: '5px',
    borderRadius: '5px',
    background: '#e2e2e2',
    zIndex: '10',
  },
  mapRedirect: {
    position: 'absolute',
    top: '27%',
    right: '13%',
    transform: 'rotate(180deg)',
    display: 'block',
    fontFamily: "'Roboto Condensed', Arial, Helvetica, sans-serif",
    fontSize: '2em',
  },
  mapRedirectLink: {
    color: 'white',
    textDecoration: 'none',
  },
  '@media only screen and  (max-width: 768px)': {
    sky: {
      height: '200vh',
    },
    sign: {
      top: '15%',
      left: '0',
    },
    grass: {
      width: '100vw',
    },
    grassBack: {
      left: '0',
      width: '100%',
      height: '100%',
    },
    grassMiddle: {
      top: '85%',
      left: '0',
      width: '100%',
      height: '100%',
      transform: 'rotate(0)',
    },
    grassFront: {
      left: '0',
      right: '0',
      width: '100%',
      height: '100%',
    },
    plates: {
      width: '100vw',
    },
    roadsign: {
      position: 'relative',
      left: '0',
    },
  },
});
